plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/asotr/Desktop/Claude 工作站/python教學"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]